version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./backups:/home/backups
